active:
  - AI
  - AO Transition
  - Automation
  - CAS Portfolio
  - CAS Service Development
  - EPA
  - ESP
  - ISD Hub
  - ITSM Integration
  - Reporting
  - ServiceNow
  - TCO Reduction
  - UiPath
reference:
  - AI Roadmap
  - AI Weekly
  - AO Consumption
  - AO Customer Renewal Strategy
  - CAS Dashboard
  - CAS for CERP
  - CAS Portfolio Governance
  - CAS Service Engineering Council
  - DD Management
  - ERP Portfolio Steering Call
  - PAM Pilot
  - RISE Ticket Flow
  - SAP Talk Q3 Checkin
  - UNICORN
archive:
  - E2E Delivery
  - SNOW Integration
manual_review:
  - AI Developer
  - CASSUPPCH
  - CMI Scoping Call
  - CPR818
  - IBM Corporation
