#!/usr/bin/env python3
from __future__ import annotations

import argparse
from pathlib import Path

from lib.notes_migration import (
    DEFAULT_REPORT_ROOT,
    DEFAULT_VAULT_ROOT,
    apply_migration_plan,
    compute_migration_plan,
    configure_logging,
    default_people_config_path,
    load_inventory,
    load_people_config,
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Apply a reviewed Apple Notes migration plan to a target Quartz vault.")
    parser.add_argument(
        "--inventory",
        type=Path,
        default=DEFAULT_REPORT_ROOT / "NOTES_INVENTORY.json",
        help="Inventory JSON generated by inventory_notes.py.",
    )
    parser.add_argument(
        "--target-root",
        type=Path,
        default=DEFAULT_VAULT_ROOT,
        help="Indexed Quartz vault root for migrated notes.",
    )
    parser.add_argument(
        "--people-config",
        type=Path,
        default=default_people_config_path(),
        help="People configuration YAML file.",
    )
    parser.add_argument(
        "--allow-basename-collisions",
        action="store_true",
        help="Override the default collision stop. Use only after manual review.",
    )
    parser.add_argument(
        "--apply",
        action="store_true",
        help="Required to perform writes. Without this flag the script prints the plan summary and exits.",
    )
    parser.add_argument(
        "--verbose",
        action="store_true",
        help="Enable debug logging.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    configure_logging(args.verbose)
    people_config = load_people_config(args.people_config)
    _, notes, _ = load_inventory(args.inventory)
    plan = compute_migration_plan(notes, people_config, args.target_root)

    print(
        "Apply summary:"
        f" {plan['summary']['notes_total']} note(s),"
        f" {plan['summary']['canonical_people_to_create']} person note(s),"
        f" {plan['summary']['collision_groups']} collision group(s)."
    )

    if not args.apply:
        print("No changes written. Re-run with --apply after review.")
        return 0

    result = apply_migration_plan(
        plan,
        {note.source_path: note for note in notes},
        args.target_root,
        people_config,
        allow_basename_collisions=args.allow_basename_collisions,
    )
    print(f"Created {len(result['created_people'])} canonical person note(s).")
    print(f"Created {len(result['created_projects'])} canonical project note(s).")
    print(f"Wrote {len(result['written_notes'])} migrated note(s).")
    print(f"Skipped {len(result['skipped_notes'])} note(s).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
