#!/usr/bin/env python3
from __future__ import annotations

import argparse
from pathlib import Path

from lib.notes_migration import DEFAULT_REPORT_ROOT, DEFAULT_VAULT_ROOT, configure_logging
from lib.relationship_updates import apply_relationship_plan, load_relationship_inventory, relationship_plan


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Apply planned relationship updates inside the migrated Quartz vault.")
    parser.add_argument(
        "--inventory",
        type=Path,
        default=DEFAULT_REPORT_ROOT / "RELATIONSHIP_INVENTORY.json",
        help="Relationship inventory JSON generated by analyze_relationships.py.",
    )
    parser.add_argument(
        "--vault-root",
        type=Path,
        default=DEFAULT_VAULT_ROOT,
        help="Indexed Quartz vault root.",
    )
    parser.add_argument(
        "--report-root",
        type=Path,
        default=DEFAULT_REPORT_ROOT,
        help="Directory for dry-run reports and backups.",
    )
    parser.add_argument(
        "--allow-basename-collisions",
        action="store_true",
        help="Override the default collision stop. Use only after review.",
    )
    parser.add_argument(
        "--apply",
        action="store_true",
        help="Required to perform writes. Without this flag the script prints the plan summary and exits.",
    )
    parser.add_argument(
        "--verbose",
        action="store_true",
        help="Enable debug logging.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    configure_logging(args.verbose)
    _, _, inventory_payload = load_relationship_inventory(args.inventory)
    plan = relationship_plan(inventory_payload, args.vault_root)
    print(
        "Apply summary:"
        f" {plan['summary']['project_notes_proposed']} project note(s),"
        f" {plan['summary']['person_files_proposed_for_enrichment']} person note(s),"
        f" {plan['summary']['source_notes_proposed_for_link_injection']} source note link update(s),"
        f" {plan['summary']['basename_collisions']} collision group(s)."
    )
    if not args.apply:
        print("No changes written. Re-run with --apply after review.")
        return 0
    result = apply_relationship_plan(
        plan,
        vault_root=args.vault_root,
        report_root=args.report_root,
        allow_basename_collisions=args.allow_basename_collisions,
    )
    print(f"Created backup at {result['backup_root']}")
    print(f"Updated {len(result['touched_files'])} file(s).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
