#!/usr/bin/env python3
from __future__ import annotations

import argparse
from pathlib import Path

from lib.notes_migration import (
    DEFAULT_REPORT_ROOT,
    DEFAULT_VAULT_ROOT,
    assert_report_outside_vault,
    configure_logging,
    compute_migration_plan,
    default_people_config_path,
    load_inventory,
    load_people_config,
    render_basename_collisions_markdown,
    render_dry_run_markdown,
    render_manual_review_markdown,
    resolve_report_path,
    write_text_output,
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate a dry-run migration plan for Apple Notes Markdown exports.")
    parser.add_argument(
        "--inventory",
        type=Path,
        default=DEFAULT_REPORT_ROOT / "NOTES_INVENTORY.json",
        help="Inventory JSON generated by inventory_notes.py.",
    )
    parser.add_argument(
        "--target-root",
        type=Path,
        default=DEFAULT_VAULT_ROOT,
        help="Indexed Quartz vault root for migrated notes.",
    )
    parser.add_argument(
        "--report-root",
        type=Path,
        default=DEFAULT_REPORT_ROOT,
        help="Output directory for runtime reports.",
    )
    parser.add_argument(
        "--people-config",
        type=Path,
        default=default_people_config_path(),
        help="People configuration YAML file.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Explicit no-op flag for parity with the apply script.",
    )
    parser.add_argument(
        "--verbose",
        action="store_true",
        help="Enable debug logging.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    configure_logging(args.verbose)
    people_config = load_people_config(args.people_config)
    _, notes, _ = load_inventory(args.inventory)
    plan = compute_migration_plan(notes, people_config, args.target_root)

    dry_run_path = resolve_report_path(args.report_root, "NOTES_DRY_RUN.md")
    manual_review_path = resolve_report_path(args.report_root, "MANUAL_REVIEW.md")
    collisions_path = resolve_report_path(args.report_root, "BASENAME_COLLISIONS.md")

    for report_path in (dry_run_path, manual_review_path, collisions_path):
        try:
            assert_report_outside_vault(report_path, args.target_root)
        except ValueError:
            pass

    write_text_output(dry_run_path, render_dry_run_markdown(plan), vault_root=args.target_root)
    write_text_output(manual_review_path, render_manual_review_markdown(plan), vault_root=args.target_root)
    write_text_output(collisions_path, render_basename_collisions_markdown(plan), vault_root=args.target_root)

    print(f"Wrote dry-run report to {dry_run_path}")
    print(f"Wrote manual review report to {manual_review_path}")
    print(f"Wrote collision report to {collisions_path}")
    print(
        "Summary:"
        f" {plan['summary']['notes_total']} note(s),"
        f" {plan['summary']['manual_review_total']} manual-review item(s),"
        f" {plan['summary']['collision_groups']} collision group(s)."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
