#!/usr/bin/env python3
from __future__ import annotations

import argparse
from pathlib import Path

from lib.notes_migration import DEFAULT_REPORT_ROOT, DEFAULT_VAULT_ROOT, configure_logging
from lib.relationship_updates import (
    load_relationship_inventory,
    relationship_plan,
    resolve_report_path,
    write_relationship_reports,
    write_relationship_inventory,
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Plan relationship updates for the migrated Quartz vault.")
    parser.add_argument(
        "--inventory",
        type=Path,
        default=DEFAULT_REPORT_ROOT / "RELATIONSHIP_INVENTORY.json",
        help="Relationship inventory JSON generated by analyze_relationships.py.",
    )
    parser.add_argument(
        "--vault-root",
        type=Path,
        default=DEFAULT_VAULT_ROOT,
        help="Indexed Quartz vault root.",
    )
    parser.add_argument(
        "--report-root",
        type=Path,
        default=DEFAULT_REPORT_ROOT,
        help="Directory for dry-run reports.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Explicit no-op flag for parity with the apply script.",
    )
    parser.add_argument(
        "--verbose",
        action="store_true",
        help="Enable debug logging.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    configure_logging(args.verbose)
    _, _, inventory_payload = load_relationship_inventory(args.inventory)
    plan = relationship_plan(inventory_payload, args.vault_root)
    report_paths = write_relationship_reports(plan, args.report_root, args.vault_root)
    plan_output = resolve_report_path(args.report_root, "RELATIONSHIP_PLAN.json")
    write_relationship_inventory(plan_output, plan)
    print(f"Wrote relationship dry-run report to {report_paths['RELATIONSHIP_DRY_RUN.md']}")
    print(f"Wrote project report to {report_paths['PROJECT_NOTES_DRY_RUN.md']}")
    print(f"Wrote people report to {report_paths['PEOPLE_NOTES_DRY_RUN.md']}")
    print(f"Wrote link report to {report_paths['LINK_INJECTION_DRY_RUN.md']}")
    print(f"Wrote manual review report to {report_paths['MANUAL_REVIEW.md']}")
    print(f"Wrote collision report to {report_paths['BASENAME_COLLISIONS.md']}")
    print(f"Wrote machine-readable plan to {plan_output}")
    print(
        "Summary:"
        f" {plan['summary']['notes_scanned']} note(s),"
        f" {plan['summary']['project_notes_proposed']} project note(s),"
        f" {plan['summary']['person_files_proposed_for_enrichment']} person note(s),"
        f" {plan['summary']['source_notes_proposed_for_link_injection']} link update(s),"
        f" {plan['summary']['manual_review_items']} manual-review item(s),"
        f" {plan['summary']['basename_collisions']} collision group(s)."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
